export default interface ISolicitudBeca {
	_id?: string,
    id?: string,
	nombres: string,
	apellidos: string,
	telefono: string,
	tipo_documento: "DNI" | "CE" | "PASAPORTE",
	numero_documento: string,
	facultad: string,
	facultadId: number,
	escuela: string,
	escuelaId: number,
	codigo: string,
    direccion: string
	email: string,
	periodo: string,
	carta_de_compromiso: string,
	historial_academico: string,
	constancia_matricula: string,
	contancia_tercio: string,
	declaracion_jurada: string,
	estado?: string,
    observaciones?: string,
	creado_en?: string,
	modificado_en?: string,    
}