import { Timestamp } from "firebase/firestore";

export interface ISolicitudRes{
    id?:number,
    estudianteId:string,
    tipoSolicitudId:number,
    idiomaId:number,
    nivelId:number,
    estadoId:number,
    periodo:string,
    alumnoCiunac:boolean,
    fechaPago: string,
    pago: number,
    numeroVoucher: string,
    imgVoucher: string,
    imgCertEstudio: string,
    digital: boolean,
    creadoEn: string,
    modificadoEn: string,
    estudiante?: {
        id: string,
        nombres: string,
        apellidos: string,
        numeroDocumento: string,
    },
    tiposSolicitud?: {
        id: number,
        solicitud: string,
        precio: number,
    },
    idioma?: {
        id: number,
        nombre: string,
    },
    nivel?: {
        id: number,
        nombre: string,
        orden: number,
    },
    estado?: {
        id: number,
        nombre: string,
        referencia: string
    },
}

export default interface Isolicitud {
    id?:string,
    estudianteId:string,
    tipo_solicitud:string,
    antiguo:boolean,
    apellidos:string,
    nombres:string,
    tipo_documento?: 'DNI' | 'CE' | 'PASAPORTE',
    escuela?: string,
    img_dni?:string,
    celular:string,
    direccion:string,
    certificado_trabajo?:string,
    codigo?:string,
    dni:string,
    email:string,
    idioma:string,
    nivel:string,
    numero_voucher?:string,
    facultad?:string,
    fecha_pago?:string,
    trabajador:boolean,
    img_voucher?:string,
    estado?:string,
    tipo_trabajador?:string,
    pago:number,
    alumno_ciunac?:boolean,
    img_cert_trabajo?:string,
    img_cert_estudio?:string,
    digital?:boolean,
    creado?:string | Timestamp
}